// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejwacrketsnxgjikurbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqd2FjcmtldHNueGdqaWt1cmJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyMDE5NzIsImV4cCI6MjA1Mzc3Nzk3Mn0.HG3KuJRiHiVbFSsJ4fQ3dODslbi30MD11uhyO-r5HzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);